# Generated by roxytest: Do not edit by hand!

# File R/xrefs_record_type.R: @tests

test_that("Function xrefs_indi() @ L23", {
  expect_equal(xrefs_indi(tidyged::sample555), paste0("@I", 1:3, "@"))
})


test_that("Function xrefs_famg() @ L29", {
  expect_equal(xrefs_famg(tidyged::sample555), paste0("@F", 1:2, "@"))
})


test_that("Function xrefs_subm() @ L35", {
  expect_equal(xrefs_subm(tidyged::sample555), paste0("@U", 1, "@"))
})


test_that("Function xrefs_sour() @ L41", {
  expect_equal(xrefs_sour(tidyged::sample555), paste0("@S", 1, "@"))
})

