# Generated by roxytest: Do not edit by hand!

# File R/get_related_records.R: @tests

test_that("Function get_spouses() @ L20", {
  expect_equal(get_spouses(tidyged::sample555, "@I1@"), "@I2@")
  expect_equal(get_spouses(tidyged::sample555, "@I2@", TRUE), "Robert Eugene Williams")
  expect_equal(get_spouses(tidyged::sample555, "@I3@"), character(0))
})


test_that("Function get_children() @ L55", {
  expect_error(get_children(tidyged::sample555, "@I4@"))
  expect_equal(get_children(tidyged::sample555, "@I1@"), "@I3@")
  expect_equal(get_children(tidyged::sample555, "@I2@", TRUE), "Joe Williams")
})


test_that("Function get_parents() @ L89", {
  expect_equal(get_parents(tidyged::sample555, "@I3@"), c("@I1@", "@I2@"))
  expect_equal(get_parents(tidyged::sample555, "@I3@", TRUE), c("Robert Eugene Williams", "Mary Ann Wilson"))
})


test_that("Function get_families_as_spouse() @ L159", {
  expect_equal(get_families_as_spouse(tidyged::sample555, "@I1@"), c("@F1@", "@F2@"))
  expect_equal(get_families_as_spouse(tidyged::sample555, "@I2@"), "@F1@")
})


test_that("Function get_families_as_child() @ L180", {
  expect_equal(get_families_as_child(tidyged::sample555, "@I3@"), c("@F1@", "@F2@"))
})


test_that("Function get_supporting_records() @ L232", {
  expect_equal(get_supporting_records(tidyged::sample555, "@I1@"), c("@S1@", "@R1@"))
})


test_that("Function get_descendants() @ L281", {
  expect_equal(get_descendants(tidyged::sample555, "@I1@"), "@I3@")
  expect_equal(get_descendants(tidyged::sample555, "@I1@", TRUE), c("@I1@","@I3@"))
  expect_equal(get_descendants(tidyged::sample555, "@I1@", TRUE, TRUE), c("@I2@","@I1@","@I3@"))
  expect_equal(get_descendants(tidyged::sample555, "@I1@", TRUE, TRUE, TRUE), c("@F1@","@F2@","@I2@","@I1@","@I3@"))
})

