# Generated by roxytest: Do not edit by hand!

# File R/get_rows.R: @tests

test_that("Function identify_section() @ L19", {
  expect_equal(identify_section(tidyged::sample555, 0, "HEAD", ""), 1:18)
  expect_equal(identify_section(tidyged::sample555, 1, "GEDC", "", first_only = TRUE), 2:5)
  expect_equal(identify_section(tidyged::sample555, 2, "FORM", "LINEAGE-LINKED"), 4:5)
  expect_equal(identify_section(tidyged::sample555, 3, "VERS", "5.5.5"), 5)
})


test_that("Function find_insertion_point() @ L74", {
  expect_equal(find_insertion_point(tidyged::sample555, "HD", 2, "VERS"), 4)
  expect_equal(find_insertion_point(tidyged::sample555, "HD", 3, "VERS"), 6)
  expect_equal(find_insertion_point(tidyged::sample555, "HD", 1, "CHAR"), 7)
})

